language: node_js
node_js:
  - "4.6"
  - "6.9"
  - "7.0"
services:
  - mongodb
cache:
  directories:
  - node_modules
git:
  depth: 3
before_script:
  - npm prune
after_script:
  - npm run report-coverage
