language: node_js
node_js:
  - "4.7"
  - "6.9"
  - "7.5"
services:
  - mongodb
cache:
  directories:
  - node_modules
git:
  depth: 3
script:
  - yarn test:check-coverage
after_script:
  - yarn report-coverage
